### ISSUE TITLE
"Add Contributor" button does not work as expected

### ISSUE THREAD

**Issue by hannahfrost** [sul-dlss/hydrus#131]
When testing hydrus-test, as a depositor creating a new item in a collection, when I click on the "Add Contributor" button, the button responds to the click and the "working, please wait" flash message appears, but then the message stops displaying, suggesting that the app is no longer "working" at it, no new empty field appears on the screen, and the button displays outlined in blue (as if in some active state).

When I push the button, I would expect a new empty field to appear and the button to return to its usual plain grey color.

**Comment by hannahfrost** [comment]
When I log back in and return to an item in which I had clicked the "Add Contributor" button, I see now that the button does effectively add a new contributor field to the item, but it never shows up in real time in the screen while editing like it used to. This must be the javascript that @cbeer mentioned at one point last week, thinking it was used in the status panel. It's not; it is used here.

**Comment by hannahfrost** [comment]
@jcoyne So this was not deployed so I can't test the fix, right? Can we push to -test before going to -prod?

**Comment by jcoyne** [comment]
@hannahfrost Chris deployed it to test earlier this afternoon.

**Comment by hannahfrost** [comment]
tested it, and it works. Thanks, @jcoyne and @cbeer
