### ISSUE TITLE
Hydrus APOs fail techMD step

### ISSUE THREAD

**Issue by hannahfrost** [sul-dlss/hydrus#161]
For example see druid:rm042kr8653

New APOs are failing to accession due to an attempt to create technical metadata during assembly, but APOs do not require techMD. The technicalMetadata robot is trying to add a blank datastream to the APO object, and dor-services is refusing to save it to the object.

This is causing a production outage for any new collections created in Hydrus

**Comment by peetucket** [comment]
From the common-accessioning robot logs it appears the error is bubbling up from dor-services gem trying to add/save a blank datastream, which is disallowed:

``` INFO [2018-04-22 09:32:17] (22497)  :: druid:hp518bp9831 processing
ERROR [2018-04-22 09:32:18] (22497)  :: Unable to save #<ActiveFedora::OmDatastream @pid="druid:hp518bp9831" @dsid="technicalMetadata" @controlGroup="M" changed="false" @mimeType="text/xml" > without content
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.2.0/gems/rubydora-1.9.1/lib/rubydora/datastream.rb:314:in `block in save'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.2.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:131:in `run_callbacks'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.2.0/gems/rubydora-1.9.1/lib/rubydora/datastream.rb:313:in `save'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.2.0/gems/active-fedora-8.4.2/lib/active_fedora/datastream.rb:51:in `save'
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.2.0/gems/dor-services-5.29.0/lib/dor/models/concerns/processable.rb:89:in `build_datastream'
/home/lyberadmin/common-accessioning/releases/20180419201059/robots/accession/abstract_metadata.rb:21:in `perform'```

**Comment by jcoyne** [comment]
@cbeer's work on activefedora 8.4 indicate that its dirty tracking is not compatible with ActiveModel 5.0 (or 5.1): https://github.com/samvera/active_fedora/pull/1309 This could indicate that AF is marking things "dirty" when they are not.

**Comment by atz** [comment]
Redeployed common-accessioning to use @jcoyne and @cbeer's ActiveFedora `8.5.0` which makes AF use the correct method of breaking callback cycles depending on version of `activesupport` loaded.  Please test to see whether that is sufficient.  If so, it makes #104 irrelevant.

**Comment by atz** [comment]
@blalbrit confirms TechMD is working as expected now.
