### ISSUE TITLE
Stop adding non-sdr-stemmed workgroups as default to APOs

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/hydrus#169]
New shibboleth work means that sdr-stemmed workgroups are required for viewing in Argo. All Hydrus APOs should switch over to sdr-stemmed default workgroups to replace the current dlss-stemmed workgroups at https://github.com/sul-dlss/hydrus/blob/1ca3ffa952c60db978a4b8ca94147e16d585a403/app/models/hydrus/admin_policy_object.rb#L95

I would recommend the following workgroups be used to replace the two dlss-stemmed workgroups currently in the code: https://github.com/sul-dlss/argo/blob/master/app/controllers/apo_controller.rb#L23

But @hannahfrost should confirm.

**Comment by hannahfrost** [comment]
Yes, confirmed. The change looks right to me. Thanks @blalbrit and @jcoyne!
