### ISSUE TITLE
Stop setting DC for apos.

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/hydrus#289]
https://github.com/sul-dlss/hydrus/blob/bcf5b2d6e97d2a9a591903a3d49f72653656ae6c/app/models/hydrus/collection.rb#L267

If we didn't need to do this, then DublinCoreService could move to common-accessioning.

**Comment by jcoyne** [comment]
@blalbrit can you remind me if we need to set the DC datastream?

**Comment by blalbrit** [comment]
@jcoyne - we don't specifically need DC for APOs (they are not - or shouldn't be - published). I don't know if there are elbow effects in the way Fedora handles DC (IIRC, it's kind of weird), but DC is not a requirement for APOs.
