### ISSUE TITLE
"Create new collection" fails

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/hydrus#29]
Behavior reported this morning - confirmed by me that in fact "create new collection" button is not working.

![screenshot 2016-04-21 09 26 59](https://cloud.githubusercontent.com/assets/796990/14716718/1cd614de-07a3-11e6-95df-e1ff4a201fd2.png)

**Comment by hannahfrost** [comment]
Fixed after re-placing the workflow object Hydrus depended on. Also updated the druid so it doesn't look like a fixture object
