### ISSUE TITLE
draft item without a title needs a placeholder title value on item list page

### ISSUE THREAD

**Issue by hannahfrost** [sul-dlss/hydrus#298]
In the past if you created a new object and left the title blank, when you viewed that object on the list of items in the collection it would insert a placeholder title ("Untitled"). 

Now there is nothing, which leaves there nothing to click on so that you can’t go back and continue editing that object.
<img width="808" alt="Screen Shot 2019-04-24 at 7 40 11 PM" src="https://user-images.githubusercontent.com/1801076/56708732-a8a40e80-66d2-11e9-94b5-a7c6166341d1.png">

Here is the collection list in production that shows the problem:
https://sdr.stanford.edu/collections/druid:md919gh6774/items

**Comment by jcoyne** [comment]
After fixing this I found there were some old records that needed reindexing:
```
> all_collections = Hydrus::Collection.dashboard_hash; 1
 => 1
> selected = all_collections.select { |pid, doc| doc[:solr]['titleInfo_title_ssm'].nil? }; 1
 => 1
> pp selected.keys; 1
```

**Comment by hannahfrost** [comment]
Thanks for the fix!
