### ISSUE TITLE
Hydrus should index all workflow objects

### ISSUE THREAD

**Issue by hannahfrost** [sul-dlss/hydrus#30]
and anything else dor-services expects to have in the index, like perhaps APOs?

@cbeer suggested this would take one week.

ultimately it would be better if Hydrus just consulted the Argo index instead of its own (but we assume that level of redesign is out of scope)

**Comment by peetucket** [comment]
I don't think this is necessary (unless there is a known bug still occuring to be investigating) -- the only workflow object that should be needed in the hydrus-solr is the hydrusAssemblyWF.

**Comment by cbeer** [comment]
I think we discovered somewhere in dor-services where it expects to find some other workflow objects.

**Comment by peetucket** [comment]
i see, even if there was no attempt to initiate them, it was still expecting them there?  i think it should be pretty easy to blindly index all workflow objects into the hydrus-solr

**Comment by cbeer** [comment]
Indeed.
