### ISSUE TITLE
"Open New Version" is broken

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/hydrus#31]
Any attempt to open new versions of objects in Hydrus produces the following squash error:

https://sul-squash-prod.stanford.edu/projects/hydrus/environments/production/bugs/81#history

And produces incomplete version metadata in DOR.

Possibly related to the request in https://jirasul.stanford.edu/jira/browse/LEGACY-2097 to remove legitimate workflow objects, or could be related to dor work at about the same time.

@hannahfrost can set priority on this work - in the meantime, assume that versioning of self-deposited objects is broken.

**Comment by hannahfrost** [comment]
Like what happened in #29. A critical workflow object was not indexed in Hydrus, and so the workflow failed. Erin manually re-indexed. 

We now have some common understanding across the SDR team and the Hybox tech team that supports Hydrus that we should check/re-index the workflow objects when a process like this fails. And we should #30 sometime too.
