### ISSUE TITLE
APO / collection race condition

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/hydrus#335]
When a new collection is created, an APO is also created for the collection. As part of the preservation ingest WF, the collection is checked to verify that the APO is available in preservation. If not, it raises an error.

![Screen Shot 2019-06-03 at 7 18 22 AM](https://user-images.githubusercontent.com/588335/58798327-54912180-85d0-11e9-9e46-a6908a86fe07.png)

In some cases, workflow processing is so fast that it produces a race condition. This issue appears intermittently in stage and production.

The simplest solution is to remove the check APO step from the workflow.

Creating ticket in Hydrus, but solution may be in another repo.

**Comment by peetucket** [comment]
See also sul-dlss/argo#1801

**Comment by peetucket** [comment]
verify-apo step doesn't exist anymore per sul-dlss/argo#1801 via sul-dlss/preservation_robots#220, so this shouldn't happen anymore
