### ISSUE TITLE
cron job making some noise re: deprecations

### ISSUE THREAD

**Issue by hannahfrost** [sul-dlss/hydrus#393]
Yesterday and today I received two automated email messages from Cron Daemon related to hydrus deprecations in stage and prod. I have never received these before. Can someone please see what might be the matter?

The subject of the message is:

> <hydrus@sul-hydrus-stage> /bin/bash -l -c 'cd /opt/app/hydrus/hydrus/releases/20200107191508 && RAILS_ENV=production bundle exec rake hydrus:cleanup_tmp --silent'

The body of today's message is:

> NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /usr/local/rvm/gems/ruby-2.5.3/specifications/passenger-5.3.2.gemspec:19.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/app/hydrus/hydrus/shared/bundle/ruby/2.5.0/specifications/rdf-1.99.1.gemspec:19.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/app/hydrus/hydrus/shared/bundle/ruby/2.5.0/specifications/xml-simple-1.1.5.gemspec:15.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/app/hydrus/hydrus/shared/bundle/ruby/2.5.0/specifications/rdf-xsd-1.99.0.gemspec:18.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/app/hydrus/hydrus/shared/bundle/ruby/2.5.0/specifications/rdf-rdfa-1.99.3.gemspec:17.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/app/hydrus/hydrus/shared/bundle/ruby/2.5.0/specifications/rdf-rdfxml-1.99.1.gemspec:17.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/app/hydrus/hydrus/shared/bundle/ruby/2.5.0/specifications/rsolr-2.2.1.gemspec:18.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/app/hydrus/hydrus/shared/bundle/ruby/2.5.0/specifications/mimemagic-0.3.3.gemspec:16.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/app/hydrus/hydrus/shared/bundle/ruby/2.5.0/specifications/validatable-1.6.7.gemspec:18.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/app/hydrus/hydrus/shared/bundle/ruby/2.5.0/specifications/sprockets-3.7.2.gemspec:19.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/app/hydrus/hydrus/shared/bundle/ruby/2.5.0/specifications/chronic-0.10.2.gemspec:19.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/app/hydrus/hydrus/shared/bundle/ruby/2.5.0/specifications/coderay-1.1.2.gemspec:21.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/app/hydrus/hydrus/shared/bundle/ruby/2.5.0/specifications/coffee-script-source-1.12.2.gemspec:16.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/app/hydrus/hydrus/shared/bundle/ruby/2.5.0/specifications/coffee-rails-4.2.2.gemspec:16.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/app/hydrus/hydrus/shared/bundle/ruby/2.5.0/specifications/orm_adapter-0.5.0.gemspec:16.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/app/hydrus/hydrus/shared/bundle/ruby/2.5.0/specifications/warden-1.2.8.gemspec:18.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/app/hydrus/hydrus/shared/bundle/ruby/2.5.0/specifications/ruby-cache-0.3.0.gemspec:15.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/app/hydrus/hydrus/shared/bundle/ruby/2.5.0/specifications/sass-3.7.4.gemspec:21.

**Comment by jcoyne** [comment]
@hannahfrost Basically it's warning that the libraries we are using are not following the best practices of the Ruby language and in the future, they may not be able to run.  I'm seeing specifically the dependency on `orm_adapter`, this hasn't been updated since 2013.

**Comment by peetucket** [comment]
looks like devise v4 uses orm

**Comment by jcoyne** [comment]
@peetucket (maybe bad) news on that front: http://blog.plataformatec.com.br/2020/01/important-information-about-our-elixir-and-ruby-open-source-projects/

**Comment by peetucket** [comment]
maybe run the job weekly instead of nightly for starters?  i thinking nightly is overkill

also, perhaps setting a cron log output location will suppress the emails?   see #394

**Comment by jmartin-sul** [comment]
@jcoyne pointed out in conversation after standup yesterday that the long term solution is to get off of ActiveFedora 8, which requires us to get off of Fedora 3.

or, as he points out, "we need to rewrite libraries to talk to fedora 3, but that's not a great choice."

**Comment by vivnwong** [comment]
Talked to Hannah, agreed that this will be addressed in the repository replacement evolution WC.
