### ISSUE TITLE
Newly registered Hydrus objects have invalid content type tag

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/hydrus#435]
<img width="1504" alt="Screen Shot 2020-05-27 at 8 42 27 AM" src="https://user-images.githubusercontent.com/92044/83027749-1c130080-9ff6-11ea-9c2e-9f8ce439a580.png">

**Comment by mjgiarlo** [comment]
This should be fixed by https://github.com/sul-dlss/dor-services-app/pull/890/files and a data remediation, which I will do in production.

**Comment by mjgiarlo** [comment]
This is the link the check if any more data needs remediation: https://argo.stanford.edu/catalog?f%5Btag_ssim%5D%5B%5D=Process+%3A+Content+Type+%3A+http%3A%2F%2Fcocina.sul.stanford.edu%2Fmodels%2Fobject.jsonld
