### ISSUE TITLE
Embargo date decreases after each save

### ISSUE THREAD

**Issue by hannahfrost** [sul-dlss/hydrus#437]
Expected behavior is for the embargo date as set by the depositor is maintained and stored as entered.

As reported by Stella Ota:

> Student submitted the thesis below. She has a publication in the works, so she is embargoing the thesis. The initial embargo date that I jotted down BEFORE editing her deposit:
> 2021-12-31 4:00 pm

> Then I clicked on “Edit Draft” and made edits (e.g. changed name order). After saving the edits, the embargo date became: 

> 2021-12-30 4:00 pm 

> Then I clicked on “Edit Draft” again to check the date. It was “2021-12-30” in the edit screen. I then clicked on “Save” and looked at the “View Draft” screen again to find the embargo date had decremented once again and now displayed: 

> 2021-12-29 4:00 pm 

> Then I checked the “History” tab, and “embargo” was listed as something that had been edited. But I had not touched the embargo date! 

> Returning to “Edit Draft”, I changed the embargo date to: 

> 2021-12-31 

> After hitting “Save”, the “View Draft” screen displayed the embargo date: 

> 2021-12-30 4:00 pm

**Comment by andrewjbtw** [comment]
Possibly out of scope for this fix, but since the embargo release runs once a day, I think we should take the hours out of the display. Even if someone expected an embargo to be released at a specific time of day, I think it only happens at midnight.

**Comment by mjgiarlo** [comment]
@hannahfrost this has been deployed to production, so Stella is clear to edit any affected objects to ensure the embargo date is as she expects. (They may require one more edit.)

FWIW, the problem wasn't on the persistence side; it was on the display side. The embargo date was persisted as e.g. 2021-12-31 but in UTC timezone, not Pacific. Then the Hydrus UI converted it to Pacific, which subtracts 7-8 hours from the time (which is MIDNIGHT of 2021-12-31) so it appeared as 4pm Pacific on 2021-12-30. The Hydrus UI should now do the right thing.

**Comment by hannahfrost** [comment]
Thanks, @mjgiarlo . Good to know it was just a display issue. Now we know that any embargoed items were released on the intended date.
