### ISSUE TITLE
Adding a depositor to a collection is not adding the collection to the user's list of active collections

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/hydrus#477]
**Describe the bug**

Since roughly mid-August, depositors and collection managers have been reporting the following issue:

1. Collection manager adds depositor to collection
2. Depositor views sdr.stanford.edu while logged in
3. Depositor does not see collection they were added to on their list of active collections
4. Depositor is nevertheless able to deposit into the collection when given a direct link to the collection URL in the hydrus interface (i.e. not the Argo URL). So the problem doesn't seem to be authorization for the collection itself.

This has affected multiple collections, including Stanford Research Data and a couple of thesis collections.

**Expected behavior**

When a depositor is added to a collection, they should see the collection listed under their list of active collections when they view sdr.stanford.edu while logged in. 

<img width="1148" alt="Screen Shot 2020-09-15 at 10 41 07 AM" src="https://user-images.githubusercontent.com/8975583/93248163-5559b280-f744-11ea-867a-72e720c21d2f.png">

**Additional context**

This issue was most recently reported on 2020-09-15. It's not clear if it affects all Hydrus collections or only certain ones. It's difficult to reproduce because every user has a different view of collections on sdr.stanford.edu

**Comment by mjgiarlo** [comment]
@andrewjbtw @amyehodge Can one of y'all add me to a new collection on both test/stage and prod? And let me know the name of the collection? Then I will begin analyzing/testing to see if I can reproduce. Thank you!

**Comment by amyehodge** [comment]
@mjgiarlo I don't know how to set up a collection in test/stage, so we'll have to ask @andrewjbtw to do this. Unless you can tell me how.

**Comment by mjgiarlo** [comment]
@amyehodge Hmm, how do you do it in prod?

**Comment by amyehodge** [comment]
@mjgiarlo At sdr.stanford.edu. Is there a parallel test/stage environment where I can do that?

**Comment by mjgiarlo** [comment]
@amyehodge :speech_balloon: 
> @mjgiarlo At sdr.stanford.edu. Is there a parallel test/stage environment where I can do that?

Yep! Try sdr-test.stanford.edu :smile:

**Comment by hannahfrost** [comment]
@amyehodge Note you will need to be on VPN to access the test system

**Comment by amyehodge** [comment]
@mjgiarlo do you want to be a depositor or a manager? I assume manager.

**Comment by amyehodge** [comment]
@mjgiarlo I created one collection in prod and one in test and added you as a manager to both. They are both called "Test Collection for Mike Giarlo."

The druid for the sdr-test collection is jj825zc3077.
The druid for the prod collection is kh207bv4040.

**Comment by mjgiarlo** [comment]
@amyehodge thank you!

**Comment by mjgiarlo** [comment]
@amyehodge :speech_balloon: 
> @mjgiarlo I created one collection in prod and one in test and added you as a manager to both. They are both called "Test Collection for Mike Giarlo."
> 
> The druid for the sdr-test collection is jj825zc3077.
> The druid for the prod collection is kh207bv4040.

OK, I see both of those collections in the UI. So far not able to reproduce. Would you mind adding me as a depositor to the Stanford Research Data Collection in prod? (I won't deposit anything into it.)

And you can dump my test collection now, if you'd like.

**Comment by amyehodge** [comment]
I've added you as a depositor to Stanford Research Data.

I don't have the power to remove the test collections once they have been saved and opened, so it will be there if you want it.

**Comment by mjgiarlo** [comment]
@amyehodge :speech_balloon: 
> I've added you as a depositor to Stanford Research Data.
> 
> I don't have the power to remove the test collections once they have been saved and opened, so it will be there if you want it.

OK, I see that one too.

**Comment by mjgiarlo** [comment]
@amyehodge @andrewjbtw I have run the code that generates the list of collections for the homepage with the affected user instance, and the druid for the stanford research data collection is indeed included. Until we can reproduce it, I'm not sure I can do to prevent it from happening again. My best guesses now as to the problem: 1) browser caching (not likely); 2) temporary indexing blip or Solr problem (much more likely).

**Comment by jcoyne** [comment]
@mjgiarlo could it be that you as a dlss developer have a different authorization path than a typical user?

**Comment by mjgiarlo** [comment]
@jcoyne I didn't think the home controller did authZ: https://github.com/sul-dlss/hydrus/blob/7700dceee162a26486dbbbac80421b83fc4406ff/app/controllers/catalog_controller.rb#L5 Could be something with Shibboleth/devise not recognizing a user and setting them as `current_user`?

**Comment by mjgiarlo** [comment]
@amyehodge @andrewjbtw is it at all possible that the user was not signed in?

**Comment by amyehodge** [comment]
@mjgiarlo, no that should not be possible.

**Comment by jcoyne** [comment]
@mjgiarlo I mean the authorization clauses that are injected into the solr query.

**Comment by mjgiarlo** [comment]
@jcoyne :speech_balloon: 
> @mjgiarlo I mean the authorization clauses that are injected into the solr query.

gotcha. then my answer is :man_shrugging:  :laughing:

**Comment by andrewjbtw** [comment]
Closing this as it has not recurred recently and doesn't seem to still be an issue.
