### ISSUE TITLE
New Hydrus APOs are being created with defaultObjectRights set to "discover"="none", which should never happen

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/hydrus#478]
Reported by @hannahfrost and @amyehodge:

New Hydrus APOs are being created with defaultObjectRights that should be impossible in Hydrus. Specifically, Hydrus objects should never have "discover" set to "none". 

```xml
<rightsMetadata>
  <access type="discover">
    <machine>
      <none/>
    </machine>
  </access>
  <access type="read">
    <machine>
      <world/>
    </machine>
  </access>
  <use>
    <human type="useAndReproduction">User agrees that, where applicable, content will not be used to identify or to otherwise infringe the privacy or confidentiality rights of individuals. Content distributed via the Stanford Digital Repository may be subject to additional license and use restrictions applied by the depositor.</human>
  </use>
  <copyright>
    <human/>
  </copyright>
</rightsMetadata>
```

Example druid: https://argo.stanford.edu/view/druid:fc704jq2575

**Impact**

The defaultObjectRights get applied to all new collections and items under that APO, so the result is that these incorrect rights are applied to all items within that collection/APO.

**Expected behavior**

The defaultObjectRights for Hydrus objects are set via the Hydrus collection form, which gives choices to make items world or stanford. The steps seem to be:

1. Create or edit a Hydrus collection
2. Behind the scenes a Hydrus APO is created or modified that uses the settings from the collection form
3. Collection and items get rights from the Hydrus APO

**Comment by mjgiarlo** [comment]
@vivnwong can you add this to the sheet and prioritize it?

**Comment by jcoyne** [comment]
@andrewjbtw Since APOs are never published, why does their access matter?

**Comment by andrewjbtw** [comment]
I added some more information on expected behavior above. Also, Hannah has checked using both "stanford" and "world" settings in the collection form and both choices are generating this error.

**Comment by mjgiarlo** [comment]
AFAICT, this behavior started in stage after 07/31 and before 08/03, and it happens at registration time. The first prod APO with this behavior appears to be https://argo.stanford.edu/view/druid:cw198jj1910 (registered 08/27---no other Hydrus APOs registered between 07/31 and 08/27).

**Comment by mjgiarlo** [comment]
The other difference I see: when defaultObjectRights has discover set to none, this XML is also added:

```xml
 <copyright>
    <human/>
  </copyright>
```

**Comment by mjgiarlo** [comment]
There were no apparently related commits in Hydrus around this time, so it's likely a change upstream (dor-services-app?).

**Comment by mjgiarlo** [comment]
I believe this commit may be the culprit: https://github.com/sul-dlss/dor-services-app/commit/7ff613bdcb990d562b1dc25435f0379e802cb638

**Comment by mjgiarlo** [comment]
@jmartin-sul I'm not going to get this wrapped after all. Maybe you and I and perhaps @jcoyne or another set of :eyes: can pair on Monday morning. This looks like an interaction between hydrus, dsa, and cocina-models. Maybe we can trace through it together.

**Comment by mjgiarlo** [comment]
And here's an integration test change I made to test this going forward: https://github.com/sul-dlss/infrastructure-integration-test/pull/153

**Comment by vivnwong** [comment]
@andrewjbtw, is this issue (the code part) fixed? Now waiting for the data remediation?

**Comment by andrewjbtw** [comment]
@vivnwong I don't know the current status of this ticket.

**Comment by vivnwong** [comment]
Sorry, I confused this issue with the other one. @mjgiarlo and @jmartin-sul, is this still in the FR queue?

**Comment by mjgiarlo** [comment]
@vivnwong according to https://docs.google.com/spreadsheets/d/10UmZVCvNoTOi3MzNhoUK72efxKUiXEQ7fcE5nsc6zRo/edit#gid=0, yes it is.

**Comment by mjgiarlo** [comment]
For @ndushay's sake, are there any updates on this from the past week, @jmartin-sul?

**Comment by ndushay** [comment]
After reading code in Hydrus and Dor-Services-app (Mike) and watching logs while creating a new hydrus collection in stage (Mike and Naomi) we believe that the default access for a collection record is being set here:  https://github.com/sul-dlss/hydrus/blame/master/app/models/hydrus/generic_object.rb#L315.   

We have deployed a branch to stage with the default access changed explicitly state world:   https://github.com/sul-dlss/hydrus/blob/hydrus-coll-prms/app/models/hydrus/generic_object.rb#L315

@andrewjbtw would you please test this on stage and see if it addresses the problem in this ticket?

@jcoyne does this seem like the correct approach?

**Comment by ndushay** [comment]
Also:  from the code, it appears this has been true for 5 months ... I'm hoping there is an Argo way to remediate the hydrus collections created over this time period.

**Comment by ndushay** [comment]
Jcoyne says:
> That seems like a reasonable fix and would explain why this only started showing up in the last 5 months.

Andrew says:
> Some collections will be Stanford only, so only “discover” can default to world. But discover should always be world for Hydrus (dark is not allowed for that system).

@andrewjbtw does this mean you want access to remain dark by default but discover (only) to be world by default?

**Comment by ndushay** [comment]
![image](https://user-images.githubusercontent.com/96775/94626200-773c5480-026f-11eb-9af3-ca68b813a43d.png)

**Comment by andrewjbtw** [comment]
@ndushay This looks good to me on stage. I created two collections, one with world and one with stanford rights, and both came out correctly.
