### ISSUE TITLE
Finish building hydrus in QA

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/hydrus#501]
To allow us to have a functioning Hydrus QA environment so that the infrastructure-integration-tests function correctly in QA.

- [x] configure solr url for QA in shared configs for hydrus-qa
- [x] create hydrus_qa Solr collection for qa environment to work
- [x] ensure that fedora sends messages to hydrus-qa for updates to its solr index
- [x] reindex any objects currently in hydrus-qa to ensure we populate the new solr index

**Comment by mjgiarlo** [comment]
There are no Hydrus items in QA, and all steps above have been done. Closing.
