### ISSUE TITLE
Minor change to label for checkbox on item edit page

### ISSUE THREAD

**Issue by hannahfrost** [sul-dlss/hydrus#65]
As a user, sometimes I want to deposit a file in my Hydrus item that I do not want to publish (just preserve), so I need to check the checkbox labeled "Hide when published" that shows up next to my uploaded file and file label field. (see screenshot)

The problem is that label is misleading to me; I interpret "Hide when published" to mean hide my file _label_ when published. 

The checkbox label should read: "Hide file when published" so it is more clear to the user what the checkbox does when checked.

![screenshot 2017-07-17 12 16 31](https://user-images.githubusercontent.com/1801076/28286080-dbb4a7ce-6aeb-11e7-8aa5-924c2129bcf3.png)

**Comment by peetucket** [comment]
fixed by #95
